// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDBd-n0_CoNciQKxC6il-GsKXN5CT-s5c',
    appId: '1:611324443636:web:b40c1bc362f27d076557a1',
    messagingSenderId: '611324443636',
    projectId: 'fitness-app-95ab6',
    authDomain: 'fitness-app-95ab6.firebaseapp.com',
    storageBucket: 'fitness-app-95ab6.appspot.com',
    measurementId: 'G-SPCJGQ6FDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNeWdgg2W7BfUiTGMZChgbe5XYUfiqluo',
    appId: '1:611324443636:android:5c9b1d917458806b6557a1',
    messagingSenderId: '611324443636',
    projectId: 'fitness-app-95ab6',
    storageBucket: 'fitness-app-95ab6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVLnni_fakDnPU8dVUoVeqwZvbuhZercc',
    appId: '1:611324443636:ios:05c44accc2102a666557a1',
    messagingSenderId: '611324443636',
    projectId: 'fitness-app-95ab6',
    storageBucket: 'fitness-app-95ab6.appspot.com',
    iosBundleId: 'com.example.fitnessapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVLnni_fakDnPU8dVUoVeqwZvbuhZercc',
    appId: '1:611324443636:ios:05c44accc2102a666557a1',
    messagingSenderId: '611324443636',
    projectId: 'fitness-app-95ab6',
    storageBucket: 'fitness-app-95ab6.appspot.com',
    iosBundleId: 'com.example.fitnessapp',
  );
}
